# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated_timestamp',
            field=models.DateField(blank=True),
        ),
    ]
