# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('Recruiter_HM', '0005_auto_20180730_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('responsibilities', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)])),
                ('qualification', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)])),
                ('overall_experience', models.CharField(choices=[('1-3', '1-3'), ('3-6', '3-6'), ('6-9', '6-9'), ('9-12', '9-12'), ('12-15', '12-15')], default='1-3', max_length=6)),
                ('secondary_skills', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(1)])),
                ('tertiary_skills', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_timestamp', models.DateTimeField()),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('primary_skills', taggit.managers.TaggableManager(help_text='comma separted tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposts',
            name='primary_skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobPosts',
        ),
    ]
