# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 06:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0006_auto_20180802_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='people',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='team',
            field=models.CharField(default='java', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
