# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 08:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0007_auto_20180807_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='overall_experience',
            field=models.CharField(choices=[('0-2', '0-2'), ('3-5', '3-5'), ('6-8', '6-8'), ('9-12', '9-12'), ('13-15', '13-15'), ('15+', '15+')], default='0-2', max_length=6),
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='primary_skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='qualification',
            field=models.CharField(max_length=2000, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tertiary_skills',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
