# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0008_auto_20180807_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='qualification',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='grad_qualification',
            field=models.CharField(choices=[('B.E', 'B.E'), ('B.Tech', 'B.Tech'), ('B.A', 'B.A'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('B.Arch', 'B.Arch'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), (' A.S ', ' A.S '), ('A.A.S', 'A.A.S'), ('A.A.T', 'A.A.T')], default='B.Tech', max_length=2000),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='pg_qualification',
            field=models.CharField(blank=True, choices=[('M.S', 'M.S'), ('MBA', 'MBA'), ('M.Tech', 'M.Tech'), ('MCA', 'MCA'), ('MCS', 'MCS'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('PHD', 'PHD')], default='', max_length=2000, null=True),
        ),
    ]
