# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 03:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0009_auto_20180807_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='grad_qualification',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='pg_qualification',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='mand_qualification',
            field=models.CharField(default='B.Tech', max_length=2000, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='opt_qualification',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
