# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 06:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0010_auto_20180808_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='mand_qualification',
            new_name='mandatory_qualification',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='opt_qualification',
            new_name='optional_qualification',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tertiary_skills',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
