# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter_HM', '0011_auto_20180808_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='optional_qualification',
            new_name='additional_qualification',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='mandatory_qualification',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='primary_skills',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
