# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 09:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recruiter_HM', '0006_auto_20180802_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pincode', models.IntegerField()),
                ('experience', models.CharField(choices=[('1-3', '1-3'), ('3-6', '3-6'), ('6-9', '6-9'), ('9-12', '9-12'), ('12-15', '12-15')], default='1-3', max_length=6)),
                ('phone', models.IntegerField()),
                ('cv_path', models.FileField(upload_to=b'')),
                ('created_timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='.')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='candidateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate'),
        ),
        migrations.AddField(
            model_name='application',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiter_HM.JobPost'),
        ),
    ]
