# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 05:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20180806_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(default=2, max_length=80, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='skill', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('0-2', '0-2'), ('3-5', '3-5'), ('6-8', '6-8'), ('9-12', '9-12'), ('13-15', '13-15'), ('15+', '15+')], default='0-2', max_length=6),
        ),
    ]
