# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20180808_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
